sudo: required

language: bash

services:
 - docker

stages:
  - compile
  - test
  - deploy

env:
  - TAG=1.8
  - TAG=1.8.3
# - TAG=1.8.7
  - TAG=1.8.8
  - TAG=1.9
  - TAG=1.9.2
  - TAG=1.9.4
  - TAG=1.10.2
  - TAG=1.11
  - TAG=1.12
  - TAG=1.12.1
  - TAG=1.12.2
  - TAG=1.13.1
  - TAG=1.13.2
  - TAG=latest

install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

compile:
  - docker build --build-arg BUKKIT_VERSION=$TAG -t bbriggs/bukkit:$TAG .

test:
  - docker run -it -p 25565:25565 -v /data:/data -e EULA=true -e TRAVIS=true bbriggs/bukkit:$TAG

deploy:
  - docker push bbriggs/bukkit:$TAG
