sudo: required

language: bash

services:
 - docker

branches:
  only: 
    - master

install: 
    - docker build -t bukkit .

script:
    - docker run -it -p 25565:25565 -v /data:/data -e EULA=true -e TRAVIS=true bukkit
