os: linux

language: bash

services:
 - docker

env:
#  - TAG=1.14 JAVA_VERSION=8
#  - TAG=1.14.1 JAVA_VERSION=8
#  - TAG=1.14.2 JAVA_VERSION=8
#  - TAG=1.14.3 JAVA_VERSION=8
  - TAG=1.14.4 JAVA_VERSION=8
#  - TAG=1.15 JAVA_VERSION=8
#  - TAG=1.15.1 JAVA_VERSION=8
  - TAG=1.15.2 JAVA_VERSION=8
#  - TAG=1.16.1 JAVA_VERSION=8
#  - TAG=1.16.2 JAVA_VERSION=8
#  - TAG=1.16.3 JAVA_VERSION=8
#  - TAG=1.16.4 JAVA_VERSION=8
  - TAG=1.16.5 JAVA_VERSION=8
#  - TAG=1.17 JAVA_VERSION=16
  - TAG=1.17.1 JAVA_VERSION=16
  - TAG=latest JAVA_VERSION=16
  
install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - ./travis-build.sh
