sudo: required

language: bash

services:
 - docker

branches:
  only: 
    - craftbukkit
    - spigot
    - master

before_install:
    - sudo mkdir /data

install: 
    - docker build -t bbriggs/bukkit:spigot-1.8.3 .

after_success:
    - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    - docker push bbriggs/bukkit:spigot-1.8.3
