sudo: required

language: bash

services:
 - docker

branches:
  only: 
    - master

install: 
    - docker build -t bbriggs/bukkit:1.8.3 .
    - docker build -t bbriggs/bukkit:latest .

after_success:
    - docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD --email=$DOCKER_EMAIL 
    - docker push bbriggs/bukkit:1.8.3
    - docker push bbriggs/bukkit:latest

notifications:
  irc:
    channels:
      - "ircs://irc.sithmail.com:6697/#minecraft"
    use_notice: true