sudo: required

language: ruby

services:
 - docker

branches:
  only: 
    - craftbukkit
    - spigot

before_install:
  - docker build -t bbriggs/bukkit:1.8.3 .
  - sudo mkdir /data
  - docker run -d -p 127.0.0.1:25565:25565 -v /data:/data -e EULA=true bbriggs/docker:1.8.3
