os: linux

language: bash

services:
 - docker

env:
#  - TAG=1.8 DOCKERFILE=Dockerfile-pre1.14
#  - TAG=1.8.3 DOCKERFILE=Dockerfile-pre1.14
#  - TAG=1.8.7 DOCKERFILE=Dockerfile-pre1.14
#  - TAG=1.8.8 DOCKERFILE=Dockerfile-pre1.14
#  - TAG=1.9 DOCKERFILE=Dockerfile-pre1.14
#  - TAG=1.9.2 DOCKERFILE=Dockerfile-pre1.14
#  - TAG=1.9.4 DOCKERFILE=Dockerfile-pre1.14
#  - TAG=1.10.2 DOCKERFILE=Dockerfile-pre1.14
#  - TAG=1.11 DOCKERFILE=Dockerfile-pre1.14
#  - TAG=1.12 DOCKERFILE=Dockerfile-pre1.14
#  - TAG=1.12.1 DOCKERFILE=Dockerfile-pre1.14
#  - TAG=1.12.2 DOCKERFILE=Dockerfile-pre1.14
#  - TAG=1.13.1 DOCKERFILE=Dockerfile-pre1.14
#  - TAG=1.13.2 DOCKERFILE=Dockerfile-pre1.14
  - TAG=1.14
  - TAG=1.14.1
  - TAG=1.14.2
  - TAG=1.14.3
  - TAG=1.14.4
  - TAG=1.15
  - TAG=1.15.1
  - TAG=1.15.2
  - TAG=1.16.1
  - TAG=1.16.2
  - TAG=1.16.3
  - TAG=1.16.4
  - TAG=1.16.5
  - TAG=1.17
  - TAG=1.17.1  
  - TAG=latest
  
install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - ./travis-build.sh
