sudo: required

language: bash

services:
 - docker

branches:
  only: 
    - craftbukkit
    - spigot
    - master

before_install:
    - sudo mkdir /data

install: 
    - docker build -t bbriggs/bukkit:spigot-1.8.3 .

after_success:
    - docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD --email=$DOCKER_EMAIL 
    - docker push bbriggs/bukkit:spigot-1.8.3
